version: '3.3'

services:
  app:
    build:
      context: .
    command: >
      sh -c "pipenv install && pipenv install --system && python manage.py collectstatic --noinput && 
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
        - 8800:8000
    volumes:
      - /var/www/admin-static:/app/statica
      - ${PWD}/.env:/app/.env:ro
      - ${PWD}/apps:/app/apps
    networks:
      - limon
  celery:
    build: .
    command: celery -A limon worker -l debug -P threads --concurrency=1
    depends_on:
      - app
    networks:
      - limon
    volumes:
      - ${PWD}/.env:/app/.env:ro
      - ${PWD}/apps/:/app/apps/:ro
      - ${PWD}/files:/app/files
      - ${PWD}:/app:ro
networks:
  limon:
    external: true

volumes:
  app-volume:
