# Generated by Django 5.0.2 on 2024-03-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantry',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantry',
            unique_together={('name', 'phone')},
        ),
    ]
