# Generated by Django 5.0.3 on 2024-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_tenantry_phone_alter_tenantry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantry',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
