# Generated by Django 5.0.3 on 2024-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
