name: CI
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: connect and pull
          uses: D3rHase/ssh-command-action@v0.2.2
          with:
              host: ${{secrets.SSH_HOST}}
              user: ${{secrets.SSH_USER}}
              private_key: ${{secrets.SSH_PRIVATE_KEY}}
              command: |
                cd ${{ secrets.LIMON_FOLDER }};
                git pull;
                docker-compose down;
                docker-compose rm -f app;
                docker-compose build --no-cache app;
                docker-compose up -d app;
